config/routes.rb
Rails.application.routes.draw do |map|
  get ":commentable_type/:commentable_id/comments", to: "comments#index", as: "comments"
  get ":commentable_type/:commentable_id/comments/new", to: "comments#new", as: "new_comment"
  get ":commentable_type/:commentable_id/comments/:id/edit", to: "comments#edit", as: "edit_comment"
  get ":commentable_type/:commentable_id/comments/:id", to: "comments#show", as: "comment"
  post ":commentable_type/:commentable_id/comments/:id", to: "comments#update"
  put ":commentable_type/:commentable_id/comments", to: "comments#create"
  delete ":commentable_type/:commentable_id/comments/:id", to: "comments#destroy"
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  field :content
  referenced_in :commentable, polymorphic: true
  referenced_in :author, class_name: "User"
  references_many :comment_attachments, dependent: :destroy

  validates_presence_of :author, :content, :commentable
  validates :commentable_type, inclusion: MongoidAjaxComments.commentables
  attr_writer :delete_attachment_ids
  after_save :save_attachments, :delete_unwanted_attachments

  def delete_attachment_ids
    @delete_attachment_ids ||= []
  end

  def attachments_files=(some_files=[])
    @attachments_to_create = some_files.map{|a| CommentAttachment.new(file: a)}
  end

  def can_be_edited_by?(some_user)
    if MongoidAjaxComments.guards[commentable_type].respond_to?(:call)
      MongoidAjaxComments.guards[commentable_type].call(self, some_user)
    else
      new_record? || (author == some_user)
    end
  end

  private

  def save_attachments
    if @attachments_to_create
      @attachments_to_create.each {|a| comment_attachments << a}
    end
  end

  def delete_unwanted_attachments
    delete_attachment_ids.each {|a_id| CommentAttachment.find(a_id).destroy}
  end
end

app/models/comment_attachment.rb
class CommentAttachment
  include Mongoid::Document
  include Mongoid::Timestamps
  referenced_in :comment
  include MongoidAjaxComments::AttachableModel 

  field :file_name
  image_accessor :file
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  layout false
  before_filter :find_commentable
  helper_method :comment_post_url, :comment_post_method

  def index
    @comments = comments_for_commentable.asc(:created_at)
  end

  def new
    @comment = Comment.new commentable: @commentable, author: current_user
  end

  def create
    @comment = Comment.new(params[:comment].merge(commentable: @commentable,
                                                  author: current_user))
    unless @comment.save
      render :new
    end
  end

  def edit
    @comment = comments_for_commentable.find(params[:id])
    check_permissions
  end

  def update
    @comment = comments_for_commentable.find(params[:id])
    check_permissions
    unless @comment.update_attributes(params[:comment].merge(commentable: @commentable,
                                                       author: current_user))
      render :edit
    end
  end

  def destroy
    @comment = comments_for_commentable.find(params[:id])
    check_permissions
    @comment.destroy
  end

  def show
    @comment = comments_for_commentable.find(params[:id])
  end

  private

  def check_permissions
    raise "Not allowed" unless @comment.can_be_edited_by?(current_user)
  end

  def find_commentable
    @commentable = params[:commentable_type].classify.constantize.find(params[:commentable_id])
  end

  def comments_for_commentable
    Comment.where(commentable_type: params[:commentable_type].classify,
                  commentable_id: params[:commentable_id])
  end

  def comment_post_url(comment)
    if comment.new_record?
      comments_path(commentable_type: @comment.commentable_type.underscore,
                    commentable_id: @comment.commentable_id)
    else
      comment_path(comment,
                   commentable_type: @comment.commentable_type.underscore,
                   commentable_id: @comment.commentable_id)
    end
  end

  def comment_post_method(comment)
    comment.new_record? ? :put : :post
  end
end

app/views/comments/_comment.html.erb
<div class="comment" id="comment_<%= comment.id %>">
  <div>
    <%= comment.content %>
  </div>
  <div>
    <% comment.comment_attachments.each do |attachment| %>
      <%= link_to attachment.file.name, attachment.file.url %>
    <% end %>
  </div>
  <%= link_to "Edit", edit_comment_path(comment,
                                        commentable_type: params[:commentable_type],
                                        commentable_id: params[:commentable_id]),
                      remote: true if comment.can_be_edited_by?(current_user) %>
  <%= link_to "Remove", comment_path(comment,
                                     commentable_type: params[:commentable_type],
                                     commentable_id: params[:commentable_id]),
                        method: "delete", remote: true if comment.can_be_edited_by?(current_user) %>

  <hr/>
</div>

app/views/comments/_create.js.erb
$("#new_comment").remove();

$("#<%= params[:commentable_type] %>_<%= params[:commentable_id] %>").append(
  '<%= escape_javascript(render @comment) %>'
);

app/views/comments/_form.html.erb
<%= form_for @comment, url: comment_post_url(@comment), html: {method: comment_post_method(@comment)} do |f| %>
  <p>
    <%= f.label :content %>
    <br/>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= label_tag "attachment", "Attachments" %>
    <br>
    <% unless @comment.comment_attachments.empty? %>
      <% @comment.comment_attachments.select {|a| !a.new_record?}.each do |attachment| %>
        <div>
          <%= link_to attachment.file.name, attachment.file.url %>
          <%= check_box_tag "comment[delete_attachment_ids][]", attachment.id,
                          f.object.delete_attachment_ids.include?(attachment.id.to_s),
                          id: "delete_#{attachment.id}" %>

          <%= label_tag "delete_#{attachment.id}", "remove?" %>
        </div>
      <% end %>
    <% end %>
    <%= file_field_tag "comment[attachments_files][]", id: "attachment" %>
  </p>
  <p>
    <%= f.submit "Post Comment" %>
    <% if f.object.new_record? %>
      <%= link_to "Cancel", "#", class: "cancel-new-comment" %>
    <% else %>
      <%= link_to "Cancel", comment_path(@comment, commentable_type: params[:commentable_type],
                                                  commentable_id: params[:commentable_id]), remote: true %>
    <% end %>
  </p>
<% end %>

app/views/comments/_update.js.erb
$("#comment_<%= @comment.id %>").replaceWith(
  '<%= escape_javascript(render @comment) %>'
);

app/views/comments/create.html.erb
<textarea>
<%= render partial: "create.js" %>
</textarea>

app/views/comments/create.js.erb
$("#new_comment").remove();

$("#<%= params[:commentable_type] %>_<%= params[:commentable_id] %>").append(
  '<%= escape_javascript(render @comment) %>'
);

app/views/comments/destroy.js.erb
$("#comment_<%=@comment.id%>").remove();

app/views/comments/edit.html.erb
<textarea>
  <%= render template: "comments/edit.js" %>
</textarea>

app/views/comments/edit.js.erb
$("#comment_<%= @comment.id %>").html('<%= escape_javascript(render partial: "form") %>');

$("#comment_<%= @comment.id %> .edit_comment").ajaxComplete(function(){
  $("#attachment").MultiFile({});
});

$("#comment_<%= @comment.id %> .edit_comment").ajaxForm({dataType: 'script'});

app/views/comments/index.html.erb
<%= link_to "Comment", new_comment_path(commentable_type: params[:commentable_type],
                                        commentable_id: params[:commentable_id]),
                       remote: true %>

<%= render @comments %>

app/views/comments/new.html.erb
<textarea>
  <%= render template: "comments/new.js" %>
</textarea>

app/views/comments/new.js.erb
$("#new_comment").remove();
$("#<%= params[:commentable_type] %>_<%= params[:commentable_id] %>").append(
'<%= escape_javascript(render partial: "form") %>'
);

$("#new_comment").ajaxComplete(function(){
  $("#attachment").MultiFile({});
});

$("#new_comment").ajaxForm({dataType: 'script'});
$('html,body').animate({ scrollTop: $("#new_comment").offset().top }, { duration: 'slow', easing: 'swing'});

app/views/comments/show.js.erb
$("#comment_<%= @comment.id %>").replaceWith('<%= escape_javascript(render @comment) %>');

app/views/comments/update.html.erb
<textarea>
<%= render partial: "update.js" %>
</textarea>